# Generated by Django 5.2.5 on 2025-08-16 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='faculty',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
