# Generated by Django 5.2.5 on 2025-08-18 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_alter_students_faculty_alter_students_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='event_id_ref',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='booking',
            name='student_name',
            field=models.CharField(default='Unknown Student', max_length=50),
        ),
    ]
